options:
    Prefix: &6&l&nRizzBox&b &7
    Message: &7Please wait &b&l2 seconds.
    CoolDown: 2 seconds

on chat:
    if {%player%.cooldown} is true:
        send "&6&l&nRizzBox&b &7 {@Message}"
        cancel event
    else:
        set {%player%.cooldown} to true
        wait {@CoolDown}
        clear {%player%.cooldown}
 
on leave:
 clear {%player%.cooldown}
on join:
 clear {%player%.cooldown}