on death:
    if attacker is a player:
        if victim is a player:
            if name of attacker's tool is set:
                set death message to "&4&l☠ &8| &c&l%attacker% &7has murdered &a&l%victim% &7with [&f&r%name of attacker's tool%&f]"
            else if name of attacker's tool is not set:
                if attacker's tool is set:
                    set death message to "&4&l☠ &8| &c&l%attacker% &7has murdered &a&l%victim% &7with &f[&r%attacker's tool%&f]"
                else:
                    set death message to "&4&l☠ &8| &c&l%attacker% &7has murdered &a&l%victim%"